### ISSUE TITLE
currently impossible to build full program + idl

### ISSUE THREAD

**Issue by billythedummy** [project-serum/multisig#16]
`anchor 0.13.0` cant be installed due to removal of branch in one of the submodules, IDL does not build with `anchor 0.14.0` due to breaking changes to `#[account(init)]` as detailed in [this comment](https://github.com/project-serum/multisig-ui/issues/4#issuecomment-912902377)

**Comment by armaniferrante** [comment]
Updated to v0.14.0 here https://github.com/project-serum/multisig/pull/17.

**Comment by billythedummy** [comment]
thank you! FYi, still running into the 0x65 issue in both the tests and the ui with the newest master
