### ISSUE TITLE
Build error: The given account is not owned by the executing program

### ISSUE THREAD

**Issue by keisukew53** [project-serum/multisig#32]
Hello,

I have bumped anchor version up to 0.19.0 and created PR.
However it has been failed by Github Actions although I don't see any issues in my changes.
fyi - https://app.travis-ci.com/github/project-serum/multisig/builds/243635147#L1552

I would be appreciated if you could review and merge it.

Thank you!

**Comment by keisukew53** [comment]
@fanatid I have resolved your feedback on my PR. Thanks!

**Comment by fanatid** [comment]
Is this issue related with #31?

**Comment by keisukew53** [comment]
@fanatid Yes, it is!

**Comment by fanatid** [comment]
Then let's close this issue and move the discussion to #31. I'll check why CI is failed.
