### ISSUE TITLE
Custom program error: 0xa5

### ISSUE THREAD

**Issue by ZhoufangErqiangu** [project-serum/multisig#50]
the log is below

    Program 11111111111111111111111111111111 invoke [1]
    Program 11111111111111111111111111111111 success
    Program msigmtwzgXJHj2ext4XJjCDmpbcMuufFb5cHuwg6Xdt invoke [1]
    Program log: Custom program error: 0xa5
    Program msigmtwzgXJHj2ext4XJjCDmpbcMuufFb5cHuwg6Xdt consumed 3591 of 200000 compute units
    Program msigmtwzgXJHj2ext4XJjCDmpbcMuufFb5cHuwg6Xdt failed: custom program error: 0xa5

i have tested on local test validator, all works well.

then failed on mainnet, please help

**Comment by fanatid** [comment]
Can you say commit on which you run the test and program id on mainnet? Is it same version?

**Comment by ZhoufangErqiangu** [comment]
i found that i have tested the 0.9.0 multisig.

the multisig on mainnet is 0.7.0.

after anchor build 0.7.0 and use its idl, all works well.

**Comment by ZhoufangErqiangu** [comment]
0x12c means you are not in the multisig signers list.

only the signer which is in the signer list can create transaction.

**Comment by ZhoufangErqiangu** [comment]
208 byte transaction is enough for spl token transfer
