### ISSUE TITLE
Instruction passed to inner instruction is too large (18446744073709551615 > 1280)' while ExecuteTransaction

### ISSUE THREAD

**Issue by omkar-bestdeveloperBTZ** [project-serum/multisig#73]
> let execute_tx;

    try {
      execute_tx = await `program.methods`
        .executeTransaction()
        .accounts({
          multisig: multisigAccount.publicKey,
          multisigSigner: multisigSigner,
          transaction: transaction.publicKey,
        })
        .remainingAccounts(
          accounts
            // Change the signer status on the vendor signer since it's signed by the program, not the client.
            .map((meta) =>
              meta.pubkey.equals(multisigSigner)
                ? { ...meta, isSigner: false }
                : meta
            )
            .concat({
              pubkey: pid2,
              isWritable: false,
              isSigner: false,
            })
        )
        // .signers([transaction, owner1])
        .rpc();
        
       
        error whiuile executing transaction SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: Program failed to complete.

        logs: [
    'Program 5ehzd27DGK9cs1XHnpLVSPBFpNvaZYfNWFENEoU9h1s4 invoke [1]',
    'Program log: Instruction: ExecuteTransaction',
    'Program 5ehzd27DGK9cs1XHnpLVSPBFpNvaZYfNWFENEoU9h1s4 consumed 8979 of 200000 compute units',
    'Program 5ehzd27DGK9cs1XHnpLVSPBFpNvaZYfNWFENEoU9h1s4 failed: Instruction passed to inner instruction is too large (18446744073709551615 > 1280)'
  ],
  
  anchor -V
anchor-cli 0.29.0
 I'm able to create multisig account, create raw tx and even sign the transaction but the execute transaction fails
        
i'm using the devnet, i see solutions to downgrade the version of solana like here:- https://solana.stackexchange.com/questions/6835/program-failed-to-complete-instruction-passed-to-inner-instruction-is-too-large
but i dont see a point as how would the cli version affect me calling methods using anchor.

although i did downgrade the version but still no luck

**Comment by omkar-bestdeveloperBTZ** [comment]
anchor-lang = "0.26.0"
solana-program = "1.14.18"

upgraded anchor lang from 0.25 to 0.26 , so that it becomes compatible with 1.14.18 version,
used cargo update -p solana-program --precise 1.14.18 & then did anchor build ,
i did check the logs that it got compiled using solana-program = "1.14.18" but after redeployment of contract , i'm getting the same error,

**Comment by omkar-bestdeveloperBTZ** [comment]
finally resolved it by upgrading every version(anchor-lang "0.28.0" , solana-program = "1.16.0"
 and using the cli version which has the most number of validators on devnet

**Comment by AFwcxx** [comment]
I'm getting the same problem.
How did you change your solana-program version to "1.16.0" ?

Using your suggestion `cargo update -p solana-program --precise 1.16.0` gives me the following:

```
error: failed to select a version for the requirement `solana-program = "~1.10.29"`
candidate versions found which didn't match: 1.16.24
location searched: crates.io index
required by package `anchor-lang v0.25.0`
    ... which satisfies dependency `anchor-lang = "^0.25.0"` (locked to 0.25.0) of package `coral-multisig v0.9.0`
perhaps a crate was updated and forgotten to be re-vendored?
```

**Comment by AFwcxx** [comment]
Hmm..
Had to change all versions.
The following works:

```
afwcxx@ubuntu:~$ cargo --version
cargo 1.68.0 (115f34552 2023-02-26)

afwcxx@ubuntu:~$ solana --version
solana-cli 1.14.18 (src:b00d18ce; feat:1879391783)

afwcxx@ubuntu:~$ anchor --version
anchor-cli 0.26.0
```

**Comment by AFwcxx** [comment]
Probably related to this:
https://github.com/solana-labs/solana/issues/31960#issuecomment-1668682153
